package me.samsuik.cannonlib.block;

import me.samsuik.cannonlib.physics.shape.Shapes;

public final class Blocks {
    public static final Block AIR = new Block("air", Shapes.EMPTY_SHAPE, -0.3f, true);
    public static final Block COBBLESTONE = new Block("cobblestone", Shapes.FULL_BLOCK, 6.0f);
    public static final Block END_STONE = new Block("end_stone", Shapes.FULL_BLOCK, 9.0f);
    public static final Block STONE = new Block("stone", Shapes.FULL_BLOCK, 6.0f);
    public static final Block SAND = new Block("sand", Shapes.FULL_BLOCK, 0.5f);
    public static final Block RED_SAND = new Block("red_sand", Shapes.FULL_BLOCK, 0.5f);
    public static final Block GRAVEL = new Block("gravel", Shapes.FULL_BLOCK, 0.6f);
    public static final Block CONCRETE_POWDER = new Block("concrete_powder", Shapes.FULL_BLOCK, 0.5f);
    public static final Block CONCRETE = new Block("concrete", Shapes.FULL_BLOCK, 1.6f);
    public static final Block LADDER = new Block("ladder", Shapes.LADDER, 0.4f);
    public static final Block MOVING_PISTON = new Block("moving_piston", Shapes.EMPTY_SHAPE, 1200.0f);
    public static final Block BEDROCK = new Block("bedrock", Shapes.FULL_BLOCK, 1200.0f);
    public static final Block WATER = new Block("water", Shapes.EMPTY_SHAPE, 1200.0f, true);
    public static final Block TRAPDOOR = new Block("trapdoor", Shapes.TRAPDOOR, 0.0f);
    public static final Block SIDE_TRAPDOOR = new Block("side_trapdoor", Shapes.SIDE_TRAPDOOR, 0.0f);
    public static final Block HANGING_SIGN = new Block("hanging_sign", Shapes.HANGING_SIGN, 0.0f);
    public static final Block SLAB = new Block("slab", Shapes.SLAB, 6.0f);
    public static final Block STAIR = new Block("stair", Shapes.STAIR, 6.0f);
    public static final Block LANTERN = new Block("lantern", Shapes.LANTERN, 0.0f);
    public static final Block HANGING_LANTERN = new Block("hanging_lantern", Shapes.HANGING_LANTERN, 0.0f);
    public static final Block FLOOR_GRINDSTONE = new Block("floor_grindstone", Shapes.FLOOR_GRINDSTONE, 0.0f);
    public static final Block WALL_GRINDSTONE = new Block("wall_grindstone", Shapes.WALL_GRINDSTONE, 0.0f);
    public static final Block CEILING_GRINDSTONE = new Block("ceiling_grindstone", Shapes.CEILING_GRINDSTONE, 0.0f);
    public static final Block CEILING_AMETHYST_CLUSTER = new Block("ceiling_amethyst_cluster", Shapes.CEILING_AMETHYST_CLUSTER, 0.0f);
    public static final Block AMETHYST_CLUSTER = new Block("amethyst_cluster", Shapes.AMETHYST_CLUSTER, 0.0f);
    public static final Block LARGE_AMETHYST_BUD = new Block("large_amethyst_bud", Shapes.LARGE_AMETHYST_BUD, 0.0f);
    public static final Block MEDIUM_AMETHYST_BUD = new Block("medium_amethyst_bud", Shapes.MEDIUM_AMETHYST_BUD, 0.0f);
    public static final Block SMALL_AMETHYST_BUD = new Block("small_amethyst_bud", Shapes.SMALL_AMETHYST_BUD, 0.0f);
    public static final Block AGE_0_COCOA = new Block("cocoa_0", Shapes.AGE_0_COCOA, 0.0f);
    public static final Block AGE_1_COCOA = new Block("cocoa_1", Shapes.AGE_1_COCOA, 0.0f);
    public static final Block AGE_2_COCOA = new Block("cocoa_2", Shapes.AGE_2_COCOA, 0.0f);
    public static final Block FLOOR_BELL = new Block("floor_bell", Shapes.FLOOR_BELL, 0.0f);
    public static final Block WALL_BELL = new Block("wall_bell", Shapes.WALL_BELL, 0.0f);
    public static final Block BETWEEN_WALL_BELL = new Block("between_bell", Shapes.BETWEEN_WALL_BELL, 0.0f);
    public static final Block CEILING_BELL = new Block("ceiling_bell", Shapes.CEILING_BELL, 0.0f);
    public static final Block CONDUIT = new Block("conduit", Shapes.CONDUIT, 0.0f);
    public static final Block POINTED_DRIPSTONE = new Block("pointed_dripstone", Shapes.POINTED_DRIPSTONE, 0.0f);
    public static final Block CHAINS = new Block("chains", Shapes.CHAINS, 0.0f);
    public static final Block RODS = new Block("rods", Shapes.RODS, 0.0f);
    public static final Block GENERIC_SKULL = new Block("skull", Shapes.GENERIC_SKULL, 0.0f);
    public static final Block PIGLIN_SKULL = new Block("piglin_skull", Shapes.PIGLIN_SKULL, 0.0f);
    public static final Block WALL_SKULL = new Block("wall_skull", Shapes.WALL_SKULL, 0.0f);
    public static final Block CHEST = new Block("chest", Shapes.CHEST, 0.0f);
    public static final Block HONEY = new Block("honey", Shapes.HONEY, 0.0f);
    public static final Block ANVIL = new Block("anvil", Shapes.ANVIL, 0.0f);
    public static final Block GLASS_PANE = new Block("glass_pane", Shapes.GLASS_PANE, 0.0f);
    public static final Block FENCE_GATE = new Block("fence_gate", Shapes.FENCE_GATE, 0.0f);
    public static final Block FENCE = new Block("fence", Shapes.FENCE, 0.0f);
    public static final Block WALL = new Block("wall", Shapes.WALL, 0.0f);
    public static final Block CANDLE_0 = new Block("candle_0", Shapes.CANDLE_0, 0.0f);
    public static final Block CANDLE_1 = new Block("candle_1", Shapes.CANDLE_1, 0.0f);
    public static final Block CANDLE_2 = new Block("candle_2", Shapes.CANDLE_2, 0.0f);
    public static final Block CANDLE_3 = new Block("candle_3", Shapes.CANDLE_3, 0.0f);
    public static final Block MUD = new Block("mud", Shapes.MUD, 0.0f);
    public static final Block BIG_DRIPLEAF_NONE = new Block("big_dripleaf_none", Shapes.BIG_DRIPLEAF_NONE, 0.0f);
    public static final Block BIG_DRIPLEAF_PARTIAL = new Block("big_dripleaf_partial", Shapes.BIG_DRIPLEAF_PARTIAL, 0.0f);
}
