package me.samsuik.cannonlib.block;

import me.samsuik.cannonlib.physics.shape.Shapes;

public final class Blocks {
    public static final Block AIR = new Block(Shapes.EMPTY_SHAPE, -0.3f, true);
    public static final Block COBBLESTONE = new Block(Shapes.FULL_BLOCK, 6.0f);
    public static final Block END_STONE = new Block(Shapes.FULL_BLOCK, 9.0f);
    public static final Block STONE = new Block(Shapes.FULL_BLOCK, 6.0f);
    public static final Block SAND = new Block(Shapes.FULL_BLOCK, 0.5f);
    public static final Block GRAVEL = new Block(Shapes.FULL_BLOCK, 0.6f);
    public static final Block CONCRETE_POWDER = new Block(Shapes.FULL_BLOCK, 0.5f);
    public static final Block CONCRETE = new Block(Shapes.FULL_BLOCK, 1.6f);
    public static final Block LADDER = new Block(Shapes.LADDER, 0.4f);
    public static final Block MOVING_PISTON = new Block(Shapes.EMPTY_SHAPE, 1200.0f);
    public static final Block BEDROCK = new Block(Shapes.FULL_BLOCK, 1200.0f);
    public static final Block WATER = new Block(Shapes.EMPTY_SHAPE, 1200.0f, true);
    public static final Block TRAPDOOR = new Block(Shapes.TRAPDOOR, 0.0f);
    public static final Block HANGING_SIGN = new Block(Shapes.HANGING_SIGN, 0.0f);
    public static final Block SLAB = new Block(Shapes.SLAB, 6.0f);
    public static final Block STAIR = new Block(Shapes.STAIR, 6.0f);
    public static final Block LANTERN = new Block(Shapes.LANTERN, 0.0f);
    public static final Block HANGING_LANTERN = new Block(Shapes.HANGING_LANTERN, 0.0f);
    public static final Block FLOOR_GRINDSTONE = new Block(Shapes.FLOOR_GRINDSTONE, 0.0f);
    public static final Block WALL_GRINDSTONE = new Block(Shapes.WALL_GRINDSTONE, 0.0f);
    public static final Block CEILING_GRINDSTONE = new Block(Shapes.CEILING_GRINDSTONE, 0.0f);
    public static final Block AMETHYST_CLUSTER = new Block(Shapes.AMETHYST_CLUSTER, 0.0f);
    public static final Block LARGE_AMETHYST_BUD = new Block(Shapes.LARGE_AMETHYST_BUD, 0.0f);
    public static final Block MEDIUM_AMETHYST_BUD = new Block(Shapes.MEDIUM_AMETHYST_BUD, 0.0f);
    public static final Block SMALL_AMETHYST_BUD = new Block(Shapes.SMALL_AMETHYST_BUD, 0.0f);
    public static final Block AGE_0_COCOA = new Block(Shapes.AGE_0_COCOA, 0.0f);
    public static final Block AGE_1_COCOA = new Block(Shapes.AGE_1_COCOA, 0.0f);
    public static final Block AGE_2_COCOA = new Block(Shapes.AGE_2_COCOA, 0.0f);
    public static final Block FLOOR_BELL = new Block(Shapes.FLOOR_BELL, 0.0f);
    public static final Block WALL_BELL = new Block(Shapes.WALL_BELL, 0.0f);
    public static final Block BETWEEN_WALL_BELL = new Block(Shapes.BETWEEN_WALL_BELL, 0.0f);
    public static final Block CEILING_BELL = new Block(Shapes.CEILING_BELL, 0.0f);
    public static final Block CONDUIT = new Block(Shapes.CONDUIT, 0.0f);
    public static final Block POINTED_DRIPSTONE = new Block(Shapes.POINTED_DRIPSTONE, 0.0f);
    public static final Block CHAINS = new Block(Shapes.CHAINS, 0.0f);
    public static final Block RODS = new Block(Shapes.RODS, 0.0f);
    public static final Block GENERIC_SKULL = new Block(Shapes.GENERIC_SKULL, 0.0f);
    public static final Block PIGLIN_SKULL = new Block(Shapes.PIGLIN_SKULL, 0.0f);
    public static final Block WALL_SKULL = new Block(Shapes.WALL_SKULL, 0.0f);
    public static final Block CHEST = new Block(Shapes.CHEST, 0.0f);
    public static final Block HONEY = new Block(Shapes.HONEY, 0.0f);
    public static final Block ANVIL = new Block(Shapes.ANVIL, 0.0f);
    public static final Block GLASS_PANE = new Block(Shapes.GLASS_PANE, 0.0f);
    public static final Block FENCE_GATE = new Block(Shapes.FENCE_GATE, 0.0f);
    public static final Block FENCE = new Block(Shapes.FENCE, 0.0f);
    public static final Block WALL = new Block(Shapes.WALL, 0.0f);
    public static final Block CANDLE_0 = new Block(Shapes.CANDLE_0, 0.0f);
    public static final Block CANDLE_1 = new Block(Shapes.CANDLE_1, 0.0f);
    public static final Block CANDLE_2 = new Block(Shapes.CANDLE_2, 0.0f);
    public static final Block CANDLE_3 = new Block(Shapes.CANDLE_3, 0.0f);
    public static final Block MUD = new Block(Shapes.MUD, 0.0f);
    public static final Block BIG_DRIPLEAF_NONE = new Block(Shapes.BIG_DRIPLEAF_NONE, 0.0f);
    public static final Block BIG_DRIPLEAF_PARTIAL = new Block(Shapes.BIG_DRIPLEAF_PARTIAL, 0.0f);
}
